firewalla/firewalla

controllers/netbot.js, lib/Bone.js, net2/HostManager.js, net2/SysManager.js, net2/config.json, net2/main.js, vpn/VpnManager.js
Each firewall box now has its own DNS entry.  this will make the reverse connection with vpn much easier.   in addition to
=> DDNS Support

net2/Discovery.js, test/test_sysmanager.js
=> add more validation to interface object

buildraw
=> Todo list of buildraw

api/bin/www
=> update port for api

net2/main.js
- removed ssh password setting, seems something is not right with upgrade processs
=> remove ssh password

buildraw4, scripts/main-run
- fixed bug in rawbuild
- skipping updating 1_0 stuff .. need better mechanism later
=> making 1_0 updates optional, need better mechanisms later

api/bin/www, buildraw4, controllers/netbot.js, etc/brofish.service, etc/fireupgrade.service, etc/firewalla.service, extension/country/country.js, extension/dhcpdump/dhcpdump.js, extension/dhcpdump/install.sh, extension/dnsmasq/dnsmasq.js, extension/sysinfo/SysInfo.js, net2/config.js, net2/config.json, scripts/bro-run, scripts/fireupgrade.sh, scripts/join_beta.sh, scripts/leave_beta.sh, scripts/main-run, sys/kickstart.js, test/config.json, test/test_dhcpdump.js, test/test_sysinfo.js
fireapi will auto start
along with other minor changes.
dhcpdump is not ready yet.
=> Move upgrade code to a separate systemctl service

api/app.js, api/bin/www, api/lib/CloudWrapper.js, api/routes/fastencipher2.js, controllers/netbot.js, encipher/lib/encipherio.js, lib/ControllerBot.js, monitor/MonitorMain.js, net2/Discovery.js, net2/SysManager.js, net2/config.js, net2/main.js, scripts/system-reset-all, sys/kickstart.js
sysManager.sysInfo[config], sysManger.sysinfo[eth0] are required to be ready before main/api/monitor process starts to use them.
this change looks big, but most of them are just replacing console.log with log.info
=> BUG: race condition on sysManager & Discovery init

api/routes/host.js, extension/ss_client/ss_client.js, hook/NewDeviceHook.js, net2/HostManager.js, net2/MessageBus.js
one client hostmanager may override one server hostmanager, so that no hostmanager is able to handle events, such as system policy change.
=> BUG: one messagebug event can only have one registered callback

scripts/monitor_arp.sh
a just works script to monitor spoofing reliability.
=> add helper script to monitor arp

scripts/check_fix_network.sh
Now it can check and fix(some of) following
* ethernet
* IP
* default gw
* DNS
* github.com
=> update check_fix_network.sh with more features

scripts/check_fix_network.sh
Reverts firewalla/firewalla#267
=> Revert "update check_fix_network.sh with more features"

README.md, buildraw4, etc/sysctl.conf, scripts/install.sh, scripts/main-start
google/bbr:
https://github.com/google/bbr
tcp_bbr: add BBR congestion control:
https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=0f8782ea14974ce992618b55f0c041ef43ed0b78
=> Enable BBR TCP congestion control

net2/HostManager.js
we absolutely should not tell router we are the router ...
=> pull critical fix of spoofing on self 

sensor/FlowUploadSensor.js
changed from 
```     
{
"mac1":[...],
"mac2":[...]
}
```   
to 
```
[
{
"mac":"mac1",
"flows":[...]
},
{
"mac":"mac2",
"flows":[...]
}
]
```
=> refine flow upload structure

scripts/sbin/setup_zram.sh
This reverts commit 61a11498655132cb924abaa5a5cd3f5b1274b529.
=> Revert "only create zram if not exists"

lib/Bone.js, scripts/fire-ping.sh, scripts/scheduled_reboot.sh
=> Rel 6 Drop

lib/Bone.js, util/DomainCategory.js
https://github.com/firewalla/firewalla/issues/533
Please merge after bone deployment: https://github.com/firewalla/fishbone/pull/22
=> intel feedback support multi-categories

util/DomainCategory.js
issue: https://github.com/firewalla/firewalla/issues/541
=> fix typo bug

etc/brotab
Reverts firewalla/firewalla#590
=> Revert "increase upgrade check frequency to once per 4 hours"

net2/SysManager.js, scripts/bro-run, scripts/fireupgrade.sh, scripts/main-start, sensor/SSDPSensor.js
* fix bug that upgrade may fail due to uncleaned lock files.
* increase the frequency of upgrade check
=> Patch on production

extension/shadowsocks/shadowsocks.js, extension/upnp/upnp.js, extension/upnp/upnptest.js, lib/Bone.js, net2/HostManager.js, net2/PolicyManager.js, vpn/VpnManager.js, vpn/view2.js
Natpmp should only be called (via upnp.js module) in main.  This little thing will open a listening port,  which can only be one in the system.
=> Natpmp support 

net2/NetBotTool.js
issue: https://github.com/firewalla/firewalla/issues/630
=> fix intel null issue

etc/50-default.conf, net2/main.js
- added rsyslog file, we may need to override the default.
=> Fixed dns policy growth problem

scripts/fire-stop
=> fire-stop will stop everything ... except earth turning around the moon

alarm/AlarmManager2.js, api/dist/api.yml, api/routes/encipher.js, api/routes/system.js, controllers/netbot.js, extension/frp/FRPManager.js, extension/frp/frp.js, extension/frp/vpnRelay.ini.template, net2/FlowManager.js, net2/HostManager.js, net2/config.json, scripts/list_traffic.js, sensor/VPNRelaySensor.js, util/TimeSeries.js
Reverts firewalla/firewalla#754
=> Revert "Revert " add time series ""

monitor/FlowMonitor.js, net2/SysManager.js
=> Patch on gaming detection

alarm/AlarmManager2.js, alarm/PolicyManager2.js, control/Block.js, extension/shadowsocks/shadowsocks.js, extension/ss_client/ss_client.js, net2/BroDetect.js, net2/DNSTool.js, net2/PolicyManager.js, sensor/BonjourSensor.js, sensor/PolicyGuardSensor.js
=> enable instant blocking

alarm/PolicyManager2.js, control/Block.js, control/DomainBlock.js, control/install_iptables_setup.sh, net2/DNSTool.js
=> refine instant blocking

alarm/AlarmManager2.js, alarm/PolicyManager2.js, control/CategoryBlock.js, control/DomainBlock.js, lib/Bone.js, sensor/IPv6DiscoverySensor.js
=> enable category block

net2/SysTool.js, scripts/fireupgrade_soft.sh, scripts/main-start
=> only run mgit recover when booting up

control/CategoryBlock.js, scripts/main-start
=>  load category from cloud 

control/CategoryBlock.js
=> remove keys after use

scripts/fireupgrade_soft.sh, scripts/main-start
=> [Bug] only run mgit recover when booting up

net2/FlowUtil.js, scripts/main-start
=> Fix Cannot read property ‘keepOriginal’ of undefined

alarm/PolicyManager2.js, control/CategoryBlock.js, control/install_iptables_setup.sh, extension/dnsmasq/dnsmasq.js, extension/httpd/app.js, extension/httpd/httpd.sh, extension/scheduler/scheduler.js, net2/main.js
=> bring back black hole and enable blue hole

control/Block.js
=> added a simple batching for ipset insertion

control/Block.js
=> ensure ipset exit before starting next one

controllers/netbot.js, net2/HostManager.js
=> portforward configuration

alarm/PolicyManager2.js, control/CategoryBlock.js, extension/dnsmasq/dnsmasq.js, extension/upnp/upnp.js, net2/main.js
=> only start policy queue in FireMain 

alarm/AlarmManager2.js
=> enable category info in policy & exception

lib/Bone.js, net2/DNSManager.js, net2/HostManager.js
=> bug fix: mainly monitor thread not returning bug 

alarm/AlarmManager2.js, api/routes/dnsmasq.js, extension/dnsmasq/dnsmasq.js, net2/Firewalla.js, net2/HostManager.js, net2/PolicyManager.js, sensor/DNSMASQSensor.js
- Assign 3C:xx:xx:xx:xx:xx to 192.168.1.x (monitored subnet):
- ```redis-cli HSET dhcp:static 3C:xx:xx:xx:xx:xx 192.168.1.x```
- Assign 3C:xx:xx:xx:xx:xx to 192.168.218.x (monitored subnet):
- ```redis-cli HSET dhcp:static 3C:xx:xx:xx:xx:xx 192.168.218.x```
- Remove static ip assignment for 3C:xx:xx:xx:xx:xx:
- ```redis-cli HDEL dhcp:static 3C:xx:xx:xx:xx:xx```
=> support mac -> static ip in dhcp mode

extension/upnp/README.md, extension/upnp/nat-pmp.js, extension/upnp/upnp.js, hook/DestIPFoundHook.js, net2/BroDetect.js, net2/IntelTool.js
=> Fixed intel with 'flow direction'.  Fixed nat-pmp bug and integrated nat-pmp into firewalla base code

control/Block.js, extension/dnsmasq/dnsmasq.js, net2/config.json
=> BUG: family resolv config not reloaded immediately after change

extension/dnsmasq/dnsmasq.js
=> BUG: dnsmasq may not start if reload occurs before start

extension/dnsmasq/dnsmasq.js
=> add --clear-on-reload in dnsmasq config

extension/httpd/app.js, monitor/FlowMonitor.js, sensor/OldDataCleanSensor.js, util/linux.js
=> Fix uncaught errors

alarm/PolicyManager2.js
=> BUG: renewed policy was invalidated by previous version policy

control/Block.js, controllers/netbot.js
Fix: https://github.com/firewalla/firewalla.ios/issues/577
=> handle unhandled error/rejection

control/Block.js, monitor/FlowMonitor.js, sensor/OldDataCleanSensor.js, util/linux.js
=> [BUG] fix some error handling issues

scripts/free-memory-lastresort
- a better way to clean up memory, firemain mean clean up ...
=> added firemain to restart list for last resort fix

scripts/free-memory-lastresort, scripts/free-memory-process
memory  / process /thread monitoring
=> memory  / process /thread monitoring

scripts/free-memory-lastresort, scripts/free-memory-process
=> add more memory checker and recover

extension/dnsmasq/dnsmasq.js
=> Fix dnsmasq fails to start issue

alarm/PolicyManager2.js
=> BUG: always throw exception when event type is incrementalUpdate

sensor/FlowAggregationSensor.js, sensor/OldDataCleanSensor.js
=> BUG: workaround to remove technology and search-portal

sensor/FlowAggregationSensor.js
=> ignore more for technology and search portal

net2/IntelManager.js
=>  more robust in handling ip info

extension/portforward/portforward.js, net2/HostManager.js
=> stability enhancements

net2/config.json
=> update version 

net2/MessageBus.js
=> ignore message bug error on JSON

net2/BroDetect.js
=> fixing burst error

scripts/free-memory-process
=> use different fireapi max memory for arm64

monitor/FlowMonitor.js, net2/main.js
=> BUG: remote ip in intelAlarm is undefined

extension/sysinfo/SysInfo.js, net2/SysManager.js, vendor_lib/osutils.js
=>  BUG: should always load subnet info from sysinfo 

controllers/netbot.js, extension/dnsmasq/dnsmasq.js, net2/PolicyManager.js
=> upstream dns feature enablement - walla side change

control/Block.js, control/CategoryBlock.js, control/CategoryUpdater.js, controllers/netbot.js, hook/DestIPFoundHook.js
=>  add category updater 

extension/upnp/README.md, extension/upnp/nat-upnp.js, extension/upnp/nat-upnp/client.js, extension/upnp/nat-upnp/device.js, extension/upnp/nat-upnp/ssdp.js, extension/upnp/nat-upnp/utils.js, extension/upnp/upnp.js, vpn/Default.txt, vpn/server_config.txt
=> vpn config fixes, upnp crash fixes and moving upnp in repo

alarm/AlarmManager2.js
=> modify de-dup 

control/CategoryUpdater.js
=> refine category blocking

hook/DeviceHook.js
=> BUG: invalid mac syntax

control/CategoryUpdater.js, controllers/netbot.js, lib/ControllerBot.js, net2/HostManager.js, net2/SysManager.js, sys/kickstart.js
=> many fixes

extension/httpd/app.js
=> BUG: invalid default redirect location

util/gsb.js
=> gsb integration

alarm/AlarmManager2.js
=> support allow/block Scan::Port_Scan rule

monitor/FlowMonitor.js
=> add whois info into alarm

controllers/netbot.js
=> provide whois and ipinfo service from walla

control/Block.js, control/CategoryUpdater.js, sensor/CategoryUpdateSensor.js
=> enable default consumer block list 

net2/BroDetect.js, scripts/free-memory-process
=> Reduce processing dns duplicated data

control/CategoryUpdater.js, hook/DestIPFoundHook.js, net2/BroDetect.js, net2/DNSTool.js, net2/IntelManager.js
=> many bug fixes

control/CategoryUpdater.js, hook/DestIPFoundHook.js, net2/BroDetect.js, net2/DNSTool.js
=>  many bug fixes

net2/BroDetect.js
=> reduce unnecessary flooding logging

extension/upnp/README.md, extension/upnp/nat-upnp.js, extension/upnp/nat-upnp/client.js, extension/upnp/nat-upnp/device.js, extension/upnp/nat-upnp/ssdp.js, extension/upnp/nat-upnp/utils.js, extension/upnp/upnp.js, net2/BroDetect.js, net2/DNSTool.js, sensor/NaughtyMonkeySensor.js
* Upnp crash
* dns burst
* monkey
=> Beta Patch May 28th

vpn/install2.sh
=> fix vpn config null bug

alarm/Alarm.js, controllers/netbot.js, extension/httpd/app.js, locales/en.json, net2/config.json, sensor/IntelReportSensor.js, sensor/OldDataCleanSensor.js
=> support intel report

alarm/AlarmManager2.js, controllers/netbot.js, extension/alexarank/alexarank.js
=> support extended alarm info 

sensor/UPNPSensor.js
=> change to use new upnp

net2/config.json
=> disable blue by default

alarm/PolicyManager2.js, control/Block.js, control/CategoryUpdater.js, lib/Bone.js, net2/BroDetect.js, net2/HostManager.js, net2/logger.js, sensor/IPv6DiscoverySensor.js, sensor/NmapSensor.js
=> refine logs

monitor/MonitorMain.js, net2/logger.js, net2/main.js
=> add heartbeat message to keep generating logs for every X minutes

util/i18n.js
=> disable set local feature, make system default to en

controllers/netbot.js, hook/DestIPFoundHook.js, scripts/free-memory-process, scripts/sbin/setup_zram.sh, sensor/HeapSensor.js
=>  BUG: Memory leak

alarm/AlarmManager2.js, net2/Firewalla.js
=> BUG: should only run alarm queue in FireMon

encipher/lib/encipherio.js, intel/WhoisIPIntel.js, lib/Bone.js, net2/logger.js, net2/main.js, sys/invitation.js
=> Patch: force some log.infos to be printed in production

monitor/MonitorMain.js, net2/main.js
=> Change heartbeat log level to INFO

alarm/AlarmManager2.js, etc/brotab, monitor/MonitorMain.js, net2/SysManager.js, net2/logger.js, net2/main.js, scripts/firemain-ping.sh, scripts/firemon-ping.sh
=> Beta Patch: Change heartbeat log level to INFO

vpn/Default.txt, vpn/VpnManager.js
=> Patch: only one vpn gen script should be running at same time

alarm/AlarmManager2.js
=> support category and device level scope on creating exception from alarm

alarm/AlarmManager2.js, alarm/PolicyManager2.js, extension/dnsmasq/dnsmasq.js, vpn/VpnManager.js
=> Patch: [DHCP Mode] Reload dnsmasq only when necessary

alarm/AlarmManager2.js, extension/dnsmasq/dnsmasq.js, scripts/firemain-ping.sh, scripts/firemon-ping.sh
Reverts firewalla/firewalla#996
=> Revert "Patch: [DHCP Mode] Reload dnsmasq only when necessary"

alarm/AlarmManager2.js, extension/dnsmasq/dnsmasq.js, scripts/firemain-ping.sh, scripts/firemon-ping.sh
Reverts firewalla/firewalla#997
=> Revert "Revert "Patch: [DHCP Mode] Reload dnsmasq only when necessary""

alarm/AlarmManager2.js
=> alarm block should support per device and category

api/bin/www, monitor/MonitorMain.js, net2/LoggerManager.js, net2/main.js
=> support wildcard in LoggerManager.setGlobalLogLevel

controllers/netbot.js, encipher/lib/encipherio.js, util/DeviceMgmtTool.js
=> delete group while resetting to factory default

lib/whois/index.js, util/Whois.js
=> Bug: FireMon crashed because domain "whois.iana.org" can't be resolved

net2/config.json, sensor/CategoryUpdateSensor.js
=> Feature: Support blocking videos

alarm/PolicyManager2.js
=> Fix policy expiration time bug in case of reboot/restart

extension/upnp/nat-upnp/client.js
=> BUG: need better error handling on natpmp

hook/DeviceHook.js
=> Defer initialization of host manager in DeviceHook

encipher/lib/encipherio.js
=> Check json validity in encipherio.js

monitor/FlowMonitor.js
=> Missing e.src.ports in intel alarm with ip address only

alarm/AlarmManager2.js
=> do not overwrite dest.name when it's already set

etc/watchdog.conf
=> Change watchdog interval to 120 seconds

etc/watchdog.conf
=>  change watchdog interval to 120 seconds

alarm/AlarmManager2.js, extension/bro/BroNotice.js, extension/monkey/interestinglogin.json, monitor/FlowMonitor.js, scripts/post_run.sh, sensor/NaughtyMonkeySensor.js
=> support ssh interesting login

controllers/netbot.js, extension/dhcp/dhcp.js
=> Add DHCP discover utility script

scripts/main-start, sys/invitation.js
=> Add uptime record at the end of main-start

extension/common/key.js
=> Exclude similar characters in generate password

controllers/netbot.js, net2/HostTool.js
=> Delete host api

hook/DestIPFoundHook.js
added secondary class and version
=> added cs and version

alarm/Policy.js
=> Category policy match fix

controllers/netbot.js, extension/frp/FRPManager.js, extension/frp/frp.js, extension/frp/frpc.service.template, net2/SysManager.js, sensor/APIRelaySensor.js, sensor/VPNRelaySensor.js, sys/kickstart.js
=> Remote support keep alive

net2/FlowManager.js, sensor/OldDataCleanSensor.js
=> Expire stats:last24 automatically

intel/UAIntel.js, monitor/FlowMonitor.js, net2/BroDetect.js, net2/IntelTool.js, net2/config.json
=> Add user agent intel in alarm detail

alarm/AlarmManager2.js, net2/HostManager.js
=> Include number of archived alarms in init data

etc/brotab, extension/bitbridge/bitbridge.js, scripts/bitbridge-ping.sh
=> Restart bitbridge4 according to mode and service status

extension/dnsmasq/dnsmasq.js, net2/config.json
=> Dns connectivity backup

controllers/netbot.js, diagnostic/selfcheck.js
=> Diagnostic utils for self check

controllers/netbot.js, diagnostic/rulecheck.js, diagnostic/selfcheck.js, net2/main.js
=> Blocking validation API

extension/ssh/ssh.js, migration/migration.js
=> Use hybrid cryptography instead of RSA alone to improve performance

vpn/VpnManager.js, vpn/confgen.sh, vpn/ovpngen.sh, vpn/server_config.txt
=> Invalidate old ovpn profile

vpn/confgen.sh
=> Generate dummy crl file if not present

controllers/netbot.js, extension/routing/routing.js, extension/vpnclient/OpenVPNClient.js, extension/vpnclient/VPNClient.js, extension/vpnclient/VPNClientEnforcer.js, extension/vpnclient/openvpn_client.service.template, extension/wifi/wifi.js, net2/HostManager.js, net2/PolicyManager.js, net2/config.json, vpn/VpnManager.js
=> DHCP & OpenVPN based VPN client

controllers/netbot.js, net2/PolicyManager.js, net2/main.js, vpn/VpnManager.js, vpn/ovpngen.sh, vpn/vpntest.js
=> Invalidate all previous ovpn profile if previous_CN does not exist

scripts/prep/06_check_ovpn_crl.sh
=> check ovpn crl in preparation scripts

scripts/fire-ping.sh
=> fire-ping try backup domains if default gateway is not responding

extension/dnsmasq/dnsmasq.js
=> Keep dnsmasq running under dhcp mode

controllers/netbot.js, extension/diag/app.js, net2/SecondaryInterface.js, net2/config.js, scripts/broadcast_booting.js, scripts/check_fix_network.sh, scripts/sanity_check.sh
#1133 
firewalla/firewalla.ios#896
=> Support customize dhcp subnet

net2/HostManager.js
=> Ignore dns server in Host.spoof

migration/RedisMigrator.js, migration/migration.js
=> Use streaming and limit parallelism to reduce memory consumption during migration

net2/ModeManager.js
=> Reload config before enable secondary interface

control/install_iptables_setup.sh, net2/Ip6tables.js, net2/Iptables.js, net2/PolicyManager.js, net2/config.json, net2/main.js, scripts/flush_iptables.sh, scripts/main-run, vpn/VpnManager.js
firewalla/firewalla.ios#841
initial flush time is brought ahead from ~1m to ~8s
=> fast iptable cleanup

alarm/PolicyManager2.js, net2/DNSTool.js, sensor/DNSMASQSensor.js
=> Remove all ips from ipset before destroying ipset for domain unblock, buffer event before dnsmasq is started in DNSMASQSensor

sys/kickstart.js
=> Power off led and send terminated info to diag server on SIGTERM for FireKick

net2/Discovery.js
=> add manufacturer for firewalla

alarm/AlarmManager2.js
firewalla/firewalla.ios/issues/998
Log now looks like:
2018-11-07 15:12:48 INFO AlarmManager2: :dedup: Dup Found! ExpirationTime: a month (2592000)
2018-11-07 15:12:48 INFO AlarmManager2: :dedup: Latest alarm happened on 2018-11-7 12:10:00, cooldown: a month (2581031.9579999447)
=> Add duplicate alarm cool down details in log

alarm/PolicyManager2.js, net2/HostManager.js
=> exclude inactive device related rules

alarm/PolicyManager2.js, api/routes/policy.js, controllers/netbot.js, net2/HostManager.js, sensor/ActiveProtectSensor.js, sensor/OldDataCleanSensor.js
firewalla/firewalla.ios#955
also corrects spelling of some policies relate functions
=> Delete related policies when deleting device

alarm/AlarmManager2.js, api/routes/intel.js
=> Sort by alarm generation time

cli/cli.js, controllers/netbot.js, controllers/netbotcli.js, monitor/FlowMonitor.js, monitor/MonitorMain.js, net2/BroDetect.js, net2/FlowManager.js, net2/FlowTool.js, net2/HostManager.js, net2/config.json, plugins/siteMonitorCore.js, sensor/DataMigrationSensor.js, sensor/FlowAggregationSensor.js
=> Change all ip-based device identity to mac-based

upgrade
Alternative approach of #1261 firewalla/firewalla.ios#1007
=> remove ~/.firewalla/config/.no_auto_upgrade on cloud pushed upgrade

net2/logger.js
`echo debug> ~/.firewalla/config/FWDEBUG` to enable debug logging on system startup
=> Enable debug log level on startup

alarm/PolicyManager2.js, controllers/netbot.js, extension/portforward/portforward.js, flow/CategoryFlowTool.js, monitor/FlowMonitor.js, net2/BroDetect.js, net2/FlowAggrTool.js, net2/FlowManager.js, net2/HostManager.js, net2/NetBotTool.js
firewalla/firewalla.ios#1015
- Delete all flows associated with specific mac address.
- Delete port forwarding bind on specific ip
=> 1015 deleting device flow

alarm/PolicyManager2.js, extension/install/diag.js, platform/blue/files/brofish.service, platform/blue/platform.sh, platform/red/files/brofish.service, platform/red/platform.sh, scripts/main-start
* need to be carefully check if the memory limitation of bro is right. too high or too low may cause problem
=> add memory limit on bro and enable nic speed info to hello

alarm/Alarm.js, alarm/AlarmManager2.js, locales/en.json, locales/zh.json, net2/config.json, sensor/UPNPSensor.js
=> add upnp alarm

alarm/Policy.js
=> return false on Policy.match() when scope doesn't match

control/CategoryUpdater.js
Reverts firewalla/firewalla#1286
=> Revert "Add category block rules into filter table"

control/CategoryUpdater.js, extension/upnp/upnp.js, extension/vpnclient/VPNClientEnforcer.js, net2/logger.js, sensor/HeapSensor.js, sensor/SensorEventManager.js
=> upnp check task will only run in FireMain

control/CategoryUpdater.js, extension/upnp/upnp.js, extension/vpnclient/VPNClientEnforcer.js, net2/logger.js, sensor/HeapSensor.js, sensor/SensorEventManager.js
Reverts firewalla/firewalla#1295
=> Revert "upnp check task will only run in FireMain"

alarm/AlarmManager2.js, alarm/Policy.js, alarm/PolicyManager2.js, api/routes/policy.js, controllers/netbot.js, net2/HostManager.js, platform/blue/BluePlatform.js, sensor/ActiveProtectSensor.js, sensor/OldDataCleanSensor.js
This PR aim to build a more Redis friendly Policy implementation.
All policies should now be considered as Policy objects within the box.
=> Policy and PolicyManager refactor

controllers/netbot.js, extension/dhcp/dhcp.js, extension/dnsmasq/dnsmasq.js, net2/HostTool.js
=> Support dhcp reservation

vpn/ovpngen.sh
=> Extend default crl days to 3600 in ovpngen.sh

controllers/netbot.js, extension/dhcp/dhcp.js, extension/dnsmasq/dnsmasq.js, migration/RedisMigrator.js
=> customized dhcp address pool

extension/dnsmasq/dnsmasq-alt.conf
=> disable DNS function of alternative dnsmasq

net2/config.json, sensor/OldDataCleanSensor.js
=> Clean categoryflow:* in OldDataCleanSensor

scripts/flush_iptables.sh
=> keep DNAT & MASQUERADE rules on DHCP mode

scripts/reset-policy
=> clear policy_active, preserve default_c policy on policy reset

net2/SysManager.js, net2/config.json, sensor/SSDPSensor.js, sensor/Sensor.js
=> SSDPSensor: return immediately on external locations

alarm/AlarmManager2.js, controllers/netbot.js
=> add alarm deletion API

extension/upnp/upnp.js
=> remove invalid reference

sensor/OldDataCleanSensor.js
and no need to clean sumflow and aggrflow, they are cleaned automatically by ttl
=> cleanup hourstats correctly

alarm/Policy.js, alarm/PolicyManager2.js, api/routes/policy.js, control/Block.js
- empty `scope`, `expire`, `cronTime` won't be presented in Policy object
- remove redundant code on policy enforcement
- rewrites some async/await
- fix small bug on test API alarm/create
=> Some rework on Policy

controllers/netbot.js
=> Backward compatibility for network interface update

api/routes/intel.js, controllers/netbot.js, hook/DestIPFoundHook.js, net2/FlowTool.js, net2/IntelTool.js, net2/NetBotTool.js, sensor/FlowAggregationSensor.js
switch to native async/await in multiple places
=> when fetching cloud intel fails, still save local intel result. 

scripts/alias.sh, scripts/apt.sh, scripts/prep/07_hide_package_upgrades.sh
=> remove upgrade info, use alias to hide apt & apt-get

controllers/netbot.js, net2/DNSManager.js, net2/Discovery.js, net2/HostManager.js, net2/PolicyManager.js, sensor/IPv6DiscoverySensor.js
firewalla/firewalla.ios#1247
check common pitfalls section
https://caolan.github.io/async/index.html
more details here
https://blog.izs.me/2013/08/designing-apis-for-asynchrony
=> ensure async calls in async.eachLimit()

net2/HostManager.js
=> Do not spoof ipv6 dns server in Host.spoof

net2/HostTool.js, sensor/OldDataCleanSensor.js
=> add alarm cleanup in OldDataCleanSensor

net2/Ip6tables.js, net2/ShieldManager.js
=> Dedup ipset add commands in updateTrustedIPSet in ShieldManager

net2/BroDetect.js
=> Convert v6 address to v4 before sending DeviceUpdate for network activity heartbeat

hook/DeviceHook.js, net2/FlowTool.js, net2/HostManager.js
=> ipv6 address missing and recent flow history sorting

net2/Spoofer.js
=> use isPrimaryInterfaceIP to determine if ip should be spoofed in Spoofer.js

api/routes/system.js, controllers/netbot.js, extension/sysinfo/SysInfo.js
this should fix the EAGAIN error popped on CloudWatch
=> make sysInfo.update() linear

controllers/netbot.js, extension/vpnclient/OpenVPNClient.js, extension/vpnclient/openvpn_client@.service.template
=> add get ovpn profile content API, and support non-alphanumeric characters in profile id

lib/intercomm.js, scripts/broadcast_booting.js, scripts/find_firewalla.js, sensor/APISensor.js, sensor/BonjourSensor.js
Should solve "EPERM 224.0.0.251:5353" error
=> add exception catch for all bonjour module

net2/HostTool.js
via CloudWatch
```
TypeError: Cannot read property 'ipv4Addr' of null
at ShieldManager._updateTrustedIPSet (/home/pi/firewalla/net2/ShieldManager.js:111:33)
at <anonymous>
```
=> forEach async fix

control/Block.js, control/install_iptables_setup.sh, testLegacy/test_block.js
only change entries created by blocking policy (entries in FW_BLOCK & FW_NAT_BLOCK)
cuts the number of entries by half
after this change
filter table
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N FW_BLOCK
-N FW_DROP
-N FW_NAT_HOLE
-N FW_SHIELD
-N FW_WHITELIST
-A FORWARD -m connmark --mark 0x1/0x1 -j FW_WHITELIST
-A FORWARD -j FW_BLOCK
-A FORWARD -m set --match-set protected_ip_set dst -j FW_SHIELD
-A FW_BLOCK -m set --match-set c_bd_default_c_set src -j FW_DROP
-A FW_BLOCK -m set --match-set c_bd_default_c_set dst -j FW_DROP
-A FW_BLOCK -m set --match-set c_bm_3_set dst -m set --match-set c_bd_3_set src -j FW_DROP
-A FW_BLOCK -m set --match-set c_bm_3_set src -m set --match-set c_bd_3_set dst -j FW_DROP
-A FW_BLOCK -m set --match-set c_bm_4_set dst -m set --match-set …
```
=> unify multiple protocol rules in iptables

control/install_iptables_setup.sh, controllers/netbot.js, extension/dnsmasq/add_iptables.template.sh, extension/dnsmasq/remove_iptables.template.sh, net2/HostManager.js, net2/Ip6tables.js, net2/Iptables.js, net2/PolicyManager.js, net2/config.json, sensor/DnsLoopAvoidanceSensor.js, sensor/SafeSearchPlugin.js
=> Support per device dns caching

alarm/PolicyManager2.js, net2/main.js
this should help solving redis MISCONF error.
=> wait until bee-queue's ready before policy enforcement

net2/ModeManager.js
=> set ip of eth0 in ModeManager and kill dhclient if alternativeInterface is set

etc/brotab, scripts/fire-ping.sh
=> add flock and timeout protection for fire-ping.sh in brotab

controllers/netbot.js, net2/HostManager.js, net2/PolicyManager.js, net2/main.js, vpn/VpnManager.js, vpn/confgen.sh, vpn/ovpngen.sh, vpn/server_config.txt
=> make vpn netmask and external port configurable, refine vpn initial configuration process

net2/Iptables.js, scripts/prep/06_check_ovpn_conf.sh, vpn/confgen.sh
=>  use execAsync in iptables.run, set crl expiration to 30 days before initial setup

controllers/netbot.js, extension/vpnclient/OpenVPNClient.js, net2/HostManager.js, scripts/sanity_check.sh, sensor/SafeSearchPlugin.js
firewalla/firewalla.ios#1586
firewalla/firewalla.ios#1577
=> multiple bug fixes for Beta 7

control/install_iptables_setup.sh, extension/portforward/portforward.js, net2/HostManager.js, net2/Iptables.js, net2/SysManager.js
=> sysManager.inMySubnets4 bug fix, port forward traces back to device mac address

alarm/AlarmManager2.js, alarm/PolicyManager2.js, net2/DNSManager.js, net2/Host.js, sys/kickstart.js
=> restart brofish accordingly in kickstart.js

net2/Firewalla.js
oops...
cannot reproduce, try to fix it like this.
=> Bug: minor, remove the newline of branch key in box sysinfo (when checkin)

extension/dnsmasq/dnsmasq.js, net2/main.js
=> BUG: should clean up devicemasq folder when booting up #1612

controllers/netbot.js, extension/dnsmasq/dnsmasq.js, extension/vpnclient/OpenVPNClient.js, extension/vpnclient/VPNClientEnforcer.js, net2/HostManager.js, vpn/Default.txt, vpn/VpnManager.js, vpn/client_conf.txt, vpn/client_connected.sh, vpn/client_disconnected.sh, vpn/confgen.sh, vpn/ovpngen.sh, vpn/ovpnrevoke.sh, vpn/server_config.txt
=> vpn site-to-site support

extension/dnsmasq/dnsmasq.js, sensor/AdblockPlugin.js, sensor/FamilyProtectPlugin.js
ERROR Dnsmasq: Update adblock filters Failed! { Error: ENOENT: no such file or directory, rename '/home/pi/.firewalla/config/dns/adblock_filter.conf.tmp' -> '/home/pi/.firewalla/config/dns/adblock_filter.conf'
=> Fix error when firemain startup

alarm/PolicyManager2.js, control/Block.js, net2/Iptables.js
Reverts firewalla/firewalla#1661
=> Revert "fix bug preventing remotePort rules form cleaning its ipset"

controllers/netbot.js, net2/HostManager.js, net2/SysManager.js, net2/main.js
Signed-off-by: Edison Liu <jasonlyc.sjtu@gmail.com>
=> add version update flag patch to beta 7

controllers/netbot.js, extension/dnsmasq/dnsmasq.js, net2/Host.js
Improve: give the user an option to customize the name in the future.
=> Expose .local domains to firewalla managed devices

extension/frp/frp.js
Do not support health check temporarily
=> Fix frpc service health check 

control/install_iptables_setup.sh, extension/dnsmasq/add_iptables.template.sh, extension/dnsmasq/dnsmasq.js, extension/dnsmasq/remove_iptables.template.sh, extension/ss_client/add_iptables_template.sh, extension/ss_client/ss_client.sh, net2/Firewalla.js, scripts/estimate_compatibility.sh, tools/dnsmasqGenerator.js
=> use 0.0.0.0 for black hole ip address

net2/config.json, sensor/BoxAliasSensor.js
added config file .firewalla/config/dnsmasq/box_alias.generated
=> resolve fire.walla to box ip

net2/main.js, sensor/BoneSensor.js, sensor/SensorLoader.js
this should fix checkin data not containing info from HostManager
=> init BoneSensor via SensorLoader in main.js

extension/vpnclient/OpenVPNClient.js, extension/vpnclient/VPNClientEnforcer.js, net2/HostManager.js
=> block non-vpn traffic if VPN client is enabled

alarm/AlarmManager2.js, controllers/netbot.js
Able to delete all archived alarms
Able to delete all active alarms
=> Able to archive all alarms

controllers/netbot.js, extension/dnsmasq/dnsmasq.js, extension/speedtest/speedtest.js
`{"download": 211793746.971787,  "upload": 199269697.4850454, "server": {"latency": 13.721, "name": "Yakima, WA", "url": "http://speedtest.wabroadband.com:8080/speedtest/upload.php", "country": "United States", "lon": "-120.5059", "cc": "US", "host": "speedtest.wabroadband.com:8080", "sponsor": "Washington Broadband", "lat": "46.6021", "id": "25239", "d": 103.53097754184583}}`
=> add server info in the networkStatus result

scripts/check_ipdomain_block.sh
=> Enhancement: a script to validate if an ip or domain is blocked by Firewalla and show the id/content of the rule #84

vpn/VpnManager.js
=> add/remove upnp port mapping for VPN if default WAN IP is private IP address

alarm/ExceptionManager.js, alarm/PolicyManager2.js, controllers/netbot.js, extension/dnsmasq/dnsmasq.js
=> Enhancement: provide api to check if a domain, ip, along with port is blocked by Firewalla #89

scripts/sanity_check.sh
=> Enhancement: in scc, merge feature config in net2/config.json with sys:features #114

alarm/PolicyManager2.js, controllers/netbot.js
- delete alarms
- delete rules
=> Enhancement: Add batch action api

alarm/Policy.js, hook/DeviceHook.js
- Bug: allow policy suppress alarm
- Bug: ipv6 address shows error
=> Bug: allow policy suppress alarm

control/DomainBlock.js
* Fixed an issue that a new device may not be spoofed right away when found
=> Beta Patch 1.966 - 4

alarm/Policy.js
…direction and action in Policy constructor
=> compare dnsmasq_only in Policy.isEqualToPolicy

controllers/netbot.js, net2/HostTool.js
https://github.com/firewalla/firewalla.ios/issues/2781
=> Bug: should auto update local domain when user update device name

net2/Host.js, net2/HostManager.js, net2/config.json, sensor/NewDeviceTagSensor.js
works for either policy:system or policy:network
```
newDeviceTag: {
state: true,
tag: 9
}
```
=> add newDeviceTag policy

net2/Ipset.js, net2/config.json, sensor/DockerSensor.js
https://firewalla.zendesk.com/knowledge/articles/360051625034/en-us?brand_id=114095132753
=> add DockerSensor for user docker route management

alarm/Exception.js
Fix exception rule match issue
=> Fix exception rule match issue

control/install_iptables_setup.sh, net2/NetworkProfileManager.js, sensor/SafeSearchPlugin.js, vpn/VpnManager.js
Make gold 1.970 forward compatible with 1.971
=> Gold Patch: 1.970 - 3

platform/navy/platform.sh, scripts/brofish-ping.sh
(cherry picked from commit 62f0d765c6ff888bec3c7af26b2c566be9abb451)
=> refine brofish-ping parameters

controllers/netbot.js, net2/SysManager.js
https://github.com/firewalla/firewalla.ios/issues/3004
=> Enhancement: Box version updated time

net2/Firewalla.js
(cherry picked from commit f4a86ada332b73cf7fdc1c5d42cc8a6d8b135227)
=> consider branch beta_9_* as alpha release

platform/gold/GoldPlatform.js
(cherry picked from commit c399cfa31070e12056b7427e3bf2c9dbdfccdab4)
=> add flow expire time to 3 days for gold

flow/TypeFlowTool.js, net2/FlowTool.js, net2/HostManager.js, net2/NetBotTool.js, util/redis_manager.js
This should cuts a lot of load time of tag/interface flow view
=> optimize key scan

scripts/prep/01_node_modules_setup.sh
* bug fix on node modules file permission
=> Blue/Red Alpha Patch 1.970 - 8

scripts/prep/01_node_modules_setup.sh
(cherry picked from commit 02546a66e93d73745b7851996fd8ec4037378628)
=> bug fix on node modules file permission

net2/FireRouter.js
(cherry picked from commit 83bb4866c6393b20407605509b7c7f4faf88a1da)
=> skip private IP check on WAN for red/blue/navy

net2/FireRouter.js
(cherry picked from commit b4634845f9421fc85483b26ddc94df6e9a2345ce)
=> skip private WAN IP check in FireRouter.js

platform/navy/hooks/before_main_run/04_change_navy_eth0_interface_conf.sh
(cherry picked from commit 11f97133f1f22949ba8adfbb3a8f82a9a22c93f0)
=> change eth0 to allow-hotplug in interfaces config on navy

net2/NetworkProfileManager.js, sensor/BonjourSensor.js
(cherry picked from commit 28b904a297577f275aebb3f27edcb9f7891e09dc)
=> convert mac to upper case in BonjourSensor and NetworkProfileManager

sensor/IntelRevalidationSensor.js
Reverts firewalla/firewalla#2997
=> Revert "throttling intel revalidation"

cli/heartbeat.js, net2/HostManager.js, net2/config.json, platform/gold/GoldPlatform.js, scripts/event_collectors/ethernet_state.sh, scripts/network_metrics.sh, sensor/NetworkStatsSensor.js
https://github.com/firewalla/firecommit/issues/132
=> Ability to collect the ethernet port throughput

net2/SysManager.js, net2/config.json, scripts/network_monitor.sh, sensor/NetworkMonitorSensor.js
https://github.com/firewalla/firecommit/issues/163
=> Collect network connectivity data on box for monitoring

scripts/sanity_check.sh
https://github.com/firewalla/firecommit/issues/189
=> add WAN connectivity failure to sanity_check.sh

sensor/EventSensor.js, sys/invitation.js
Example of an event generated
```
2021-01-25 11:25:49 INFO EventApi: adding event {"ts":1611545149525,"event_type":"action","action_type":"phone_paired","action_value":1,"labels":{"eid":"80SSMn0wY8LSYjg_c2xyEg"}} at 1611545149525
```
=> fire event upon phone paired

event/EventApi.js, sensor/EventSensor.js
https://github.com/firewalla/firecommit/issues/118#issuecomment-766497318
=> enable reverse order of list events result

api/routes/flow.js, control/CategoryUpdater.js, controllers/netbot.js, extension/portforward/portforward.js, lib/Bone.js, net2/AuditTool.js, net2/FlowTool.js, net2/HostManager.js, net2/HostTool.js, net2/LogQuery.js, net2/NetworkProfile.js, net2/SysManager.js, sensor/ACLAuditLogPlugin.js, sensor/FlowAggregationSensor.js, sensor/ICMP6Sensor.js, sensor/LiveStatsPlugin.js, sensor/PublicIPSensor.js, vpn/VpnManager.js
Reverts firewalla/firewalla#3196
=> Revert "include inbound traffic in block history/stats"

scripts/clean_log.sh
https://github.com/firewalla/general_issues/issues/449
=> clean * instead of *.log under /log/forever and /log/firewalla

net2/FlowAggrTool.js, sensor/FlowAggregationSensor.js
https://github.com/firewalla/firewalla/pull/3319 changed data structure which will cause app crash
=> use array for port & devicePort on aggregation data

scripts/firereset_debug.sh
(cherry picked from commit 2a90f8fad7347e7c62894282569a8135e2fdd992)
=> add ip a and ip r to the debug output

etc/crontab, etc/crontab.gold, scripts/clean_log.sh
(cherry picked from commit 9681055455bc2f7c003e89a7631346c908c6b310)
=> refine log cleanup

extension/wireguard/wireguard.js, sensor/WireGuardPlugin.js
(cherry picked from commit 66444a67af4e152cabc7799c6bf6b7f6b066e8fb)
=> fix ip address cidr in wireguard.js

net2/FireRouter.js
(cherry picked from commit 52e1d8c763d8a57513380e490dab690bbcb02b30)
=> should also restart firereset when switch branch

scripts/clean_log.sh
(cherry picked from commit e069c1eaf18f0f3940c408211ca00e1546a26882)
=> use find instead of "bash argument" for cleanup

sensor/LiveStatsPlugin.js
(cherry picked from commit e371e7fc81878e5c480e1165cdf4b40463a0f765)
=> catch error if interface not available for stats

net2/Host.js, net2/config.json, sensor/DeviceSTPSensor.js
https://github.com/firewalla/firecommit/issues/578
=> add DeviceSTPSensor to scan stp port of each device

control/CategoryUpdater.js, control/CategoryUpdaterBase.js, control/DomainBlock.js, sensor/CategoryUpdateSensor.js
https://github.com/firewalla/firecommit/issues/572
=> sync domain IP mappings redis set in CategoryUpdater.recycleIPSet

controllers/netbot.js, net2/HostManager.js
https://github.com/firewalla/firecommit/issues/121
=> support creating MAC-based device from api

alarm/PolicyManager2.js, control/Block.js, control/install_iptables_setup.sh, extension/clash_tun/clash_tun.js, net2/Host.js, net2/Identity.js, net2/NetworkProfile.js, net2/Tag.js
https://github.com/firewalla/firecommit/issues/524
=> add sub priority chain to qos and route rules

controllers/netbot.js, net2/AuditTool.js, net2/FlowTool.js, net2/LogQuery.js
use ltype:flow for dns:accept logs
add type:tls for TLS blocks
add type:ip for lagacy flows
=> Flow API adjustments

scripts/techsupport
https://github.com/firewalla/firesecommit/issues/2
=> remove unnecessary files from techsupport

controllers/netbot.js, extension/vpnclient/OCVPNClient.js, extension/vpnclient/OpenVPNClient.js, extension/vpnclient/oc_hook.sh, extension/vpnclient/oc_start.sh, extension/vpnclient/openconnect_client@.service.template, net2/HostManager.js, scripts/prep/06_check_ovpn_conf.sh, scripts/utils.sh
https://github.com/firewalla/firecommit/issues/633
=> support ssl vpn client using openconnect

net2/PolicyManager.js
that may mislead the system that the policy was updated, but actually
it was not
(cherry picked from commit a94d09a126df024a48cf3d1e44fecef32770d3a2)
=> fixed bug that policy data may be altered by applyPolicy function

net2/BroDetect.js, net2/HostManager.js, sensor/ACLAuditLogPlugin.js, util/TimeSeries.js
https://github.com/firewalla/firecommit/issues/804
=> [Bug] monthly data usage may decrease for timezones behind GMT+0 

controllers/netbot.js, net2/NetworkTool.js, net2/config.js
Add api to reset alternative network interface to dhcp mode. (Need box restart to take effect)
Add "assignment" field in "network" section for GUI to determine current setting state "dhcp" or "static"
=> Add api to reset altenative network interface to dhcp mode

api/routes/host.js, cli/cli.js, controllers/netbot.js, monitor/FlowMonitor.js, net2/BroDetect.js, net2/FlowManager.js, net2/HostManager.js, net2/IdentityManager.js, plugins/siteMonitorCore.js, testLegacy/flow.js, testLegacy/policytest.js
This cuts size of init data by 15%
=> remove 24h stats from flowsummary

hook/DeviceHook.js, net2/VipManager.js, net2/identity/VIPProfile.js
Stop updating host mac info on virtual ip device update.
Add lastActiveTimestamp in vipProfiles.
=> Stop updating host mac info on virtual ip device update.

alarm/AlarmManager2.js, alarm/CategoryMatcher.js, alarm/Exception.js, alarm/ExceptionManager.js, controllers/netbot.js, util/scheduler.js
Support match target list in exception
=> Support target list in mute

cli/heartbeat.js
(cherry picked from commit d1a09324b2f7ad47e47f9b8988636eaf8fa24fe4)
=> add df -hi

control/CategoryExaminer.js, control/CategoryUpdater.js, control/CategoryUpdaterBase.js, control/DomainBlock.js, etc/intelproxy.service, hook/DestIPFoundHook.js, net2/config.json, sensor/CategoryUpdateSensor.js, util/util.js
=> Download category data, update hit/passthrough set.

sensor/GuardianSensor.js
- add mspId in guardian related events
- only lock if msp is not equal with self
=> add mspId in guardian related events

alarm/AlarmManager2.js, hook/DestIPFoundHook.js
* dnsproxy use dns block by default when creating policy rule
* fixed an intel bug on domain is null
=> patch to beta 9 staging 7

alarm/AlarmManager2.js, hook/DestIPFoundHook.js
Reverts firewalla/firewalla#4332
=> Revert "patch to beta 9 staging 7"

alarm/TrustManager.js, sensor/DNSProxyPlugin.js
(cherry picked from commit 9cbd5f1f6534d0d1eb8cd458ebc4a5a89ea9c6ba)
=> add trust domain to passthrough key

net2/config.json
(cherry picked from commit 60384aed30ef0bac52731243ebcd72eb66cf9bd0)
=> add unbound to config.json

.github/workflows/webpack.yml
(cherry picked from commit 48fa625061d3ddca4ee525747207dbdacdc7c41b)
=> [github action] force use same node version

alarm/AlarmManager2.js, alarm/ExceptionManager.js, sensor/DataUsageSensor.js
1. add p.intf.id to large bandwidth usage alarm
2. do not change p.tag.ids to array in original exception data in ExceptionManager._saveException
=> multiple bug fixes

net2/HostManager.js, sensor/Guardian.js
=> add guardians to initData

control/install_iptables_setup.sh, net2/NetworkProfile.js
(cherry picked from commit 6d6cd5df2812220bba531cadf81556abbbf6ffcb)
=> only drop INVALID packets if it is transmitted to WAN interface

net2/Host.js, sensor/AccountingPlugin.js, sensor/DeviceIdentificationSensor.js, sensor/InternalScanSensor.js
also parse `openports` & `screenTime` on Host creation
=> add host.detect to api return

extension/dnsmasq/dnsmasq.js, net2/Host.js, net2/HostManager.js
fix a racing condition on host update
reduce number of host object generated on dnsmasq init
=> fix a bug that hosts file won't update on device delete

extension/dnsmasq/dnsmasq.js, extension/dnsmasq/install.sh, scripts/switch_branch.sh
also reverts change on switch_branch.sh
=> use a different dhcp-hostsdir, flush legacy hosts files on setup

extension/flow/HttpFlow.js, monitor/FlowMonitor.js, net2/Host.js, net2/config.json, sensor/DeviceIdentificationSensor.js, sensor/OldDataCleanSensor.js
add feature hook to detection sensor
use host:user_agent to boost detection, and deprecate this key, remove flow:http
add clean up for host:user_agent2
=> Multiple detect related issues

control/CategoryUpdater.js, control/DomainUpdater.js, controllers/netbot.js, extension/dnscrypt/dnscrypt.js, net2/Host.js, net2/HostManager.js, net2/Monitorable.js, sensor/CategoryUpdateSensor.js
remove adblock, safeSearch from reset
avoid reset of DNSBooster on local DNS server
fix issue on native family policy reset
splits Domain:Flush from Category:Flush
=> fix multiple issues for policy:reset

scripts/sanity_check.sh
alone with multiple enhancement from shellcheck
=> make scc working on navy again

net2/Host.js, net2/HostManager.js, net2/Monitorable.js, sensor/DeviceServiceScanSensor.js
This reverts commit 0ef8d8df4779df21697df95ff95cbf139be78a36.
=> Revert "disable device port scan on all devices by default"

sensor/SafeSearchPlugin.js
=> sync gold 1.978 staging

sensor/InternalScanSensor.js
=> sync blue+ 1.978 staging

sensor/InternalScanSensor.js
=> sync purple 1.978 staging

sensor/InternalScanSensor.js
=> sync gse 1.978 staging

extension/dnsmasq/dnsmasq.js, tests/test_dnsmasq.js
Associated with https://github.com/firewalla/firecommit/issues/3245
=> Keep dns redirect rules if upstream DNS down

extension/vpnclient/VPNClient.js, tests/test_vpnclient.js
Associated with https://github.com/firewalla/firecommit/issues/3261
=> Add `dnsServers` to vpn client metadata

sensor/InternetSpeedtestPlugin.js
Related to
https://github.com/firewalla/firecommit/issues/3288
=> Add speedtest nameserver option

control/iptables_common.sh
Associated with
https://github.com/firewalla/firecommit/issues/3302
=> Drop inbound blocked tcp packet

alarm/Policy.js, alarm/PolicyManager2.js, tests/test_policymngr2.js
Related to
https://github.com/firewalla/firecommit/issues/3311
=> Reorder policy rules inbound block first

alarm/PolicyManager2.js, tests/test_policymngr2.js
Related to
https://github.com/firewalla/firecommit/issues/3311
=> Fix policy filter func refactor

etc/logrotate.d/wgvpn.logrotate, etc/rsyslog.d/41-wireguard.conf, extension/vpnclient/WGVPNClient.js, scripts/prep/06_setup_wg_kernlog.sh, scripts/prep/08_update_wgvpn_logrotate.sh, tests/test_wgvpnclient.js
Related to
https://github.com/firewalla/firecommit/issues/3330
=> Setup wireguard kern log

sensor/ACLAuditLogPlugin.js, sensor/RuleStatsPlugin.js
https://github.com/firewalla/firecommit/issues/3347
=> fix hitcount inaccurate bug

control/Block.js, controllers/netbot.js, net2/BroDetect.js, net2/Constants.js, net2/FlowTool.js, scripts/prep/06_setup_wg_kernlog.sh, sensor/ACLAuditLogPlugin.js, tests/sample_data.js, tests/test_acl_auditlog.js, tests/test_brodetect.js, tests/test_flow_tool.js, tests/test_netbot.js, tests/test_wgvpnclient.js
Related to
https://github.com/firewalla/firecommit/issues/3342
=> Add rule id to flows

net2/BroDetect.js, tests/test_brodetect.js
Related to
https://github.com/firewalla/firecommit/issues/3342
=> Fix flow null conn entry

etc/rsyslog.d/41-wireguard.conf
Related to
https://github.com/firewalla/firecommit/issues/3330
=> Stop wg server syslog

net2/config.json, sensor/SafeSearchPlugin.js, tests/test_safesearch_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3346
> **DO NOT** MERGE before dnsmasq cname$label support confirmed
=> Add cname safe search support

sensor/ACLAuditLogPlugin.js, sensor/RuleStatsPlugin.js, tests/test_acl_auditlog.js, tests/test_rule_stats_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3342
=> Add global policy id to flow

etc/rsyslog.d/41-wireguard.conf
Related to
[3330](https://github.com/firewalla/firecommit/issues/3330)
=> Fix wg profile match

net2/Constants.js, net2/identity/WGPeer.js, sensor/WgvpnConnSensor.js, tests/test_policymngr2.js, tests/test_wgpeer.js
Related to
[3432](https://github.com/firewalla/firecommit/issues/3432)
=> Set latest handleshake timestamp of wg peers

net2/LogQuery.js
This reverts commit a3e848927ed23087d4f8196585207997c8006bb0.
=> Revert "refine noise filter to only show well-known or with category"

sensor/InternetSpeedtestPlugin.js, tests/test_speedtest_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3465
=> Fix retry run internet speedtest

net2/config.json, sensor/InternalScanSensor.js, tests/test_internal_scan_sensor.js, util/requestWrapper.js
Related to
https://github.com/firewalla/firecommit/issues/3463
https://github.com/firewalla/firecommit/issues/3450
https://github.com/firewalla/firecommit/issues/3435
=> Enhance scan weak password

net2/Monitorable.js, net2/TagManager.js, net2/config.json, sensor/InternalScanSensor.js, tests/test_internal_scan_sensor.js, tests/test_tag_manager.js
Related to
https://github.com/firewalla/firecommit/issues/3529
=> Add cron job of weak password scan

extension/dhcp/dhcp.js, extension/nmap/nseConfig.json, net2/Constants.js, net2/HostManager.js, net2/config.json, platform/all/files/assets.lst, sensor/InternalScanSensor.js, sensor/NseScanPlugin.js, tests/test_dhcp.js, tests/test_internal_scan_sensor.js, tests/test_nse_scan_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3561
(https://github.com/firewalla/firecommit/issues/3546)
=> Add host nse scan result

alarm/Alarm.js, alarm/AlarmManager2.js, controllers/netbot.js, net2/Constants.js, net2/HostManager.js, net2/Monitorable.js, net2/config.js, net2/config.json, sensor/AlarmSensor.js, sensor/Guardian.js, tests/test_alarm_manager2.js, tests/test_config.js
Related to
[3583](https://github.com/firewalla/firecommit/issues/3583)
([3575](https://github.com/firewalla/firecommit/issues/3575),  [3572](https://github.com/firewalla/firecommit/issues/3572))
=> Add alarm state msp sync

alarm/AlarmManager2.js, controllers/netbot.js, extension/dhcp/dhcp.js, net2/config.js, platform/all/files/assets.lst, platform/gold/files/u18/assets.lst, sensor/Guardian.js, sensor/GuardianSensor.js, sensor/NseScanPlugin.js, tests/test_config.js, tests/test_dhcp.js
Related to
[#3583](https://github.com/firewalla/firecommit/issues/3583)
[#3561](https://github.com/firewalla/firecommit/issues/3561)
=> Fix data sync

alarm/PolicyManager2.js, control/CategoryUpdater.js, extension/dnsmasq/dnsmasq.js, intel/SSLIntel.js, lib/Bone.js, net2/config.js, sensor/CategoryExaminerPlugin.js, sensor/CategoryUpdateSensor.js, tests/test_bone.js, tests/test_category_examiner_sensor.js, tests/test_category_update_sensor.js, tests/test_intel_local_cache_sensor.js, tests/test_policymngr2.js
Related to
https://github.com/firewalla/firecommit/issues/3405
=> Add support for policy useBf option

alarm/AlarmManager2.js, sensor/CategoryExaminerPlugin.js, tests/test_alarm_manager2.js
Related to
[#3583](https://github.com/firewalla/firecommit/issues/3583)
=> Fix alarm default config

alarm/PolicyManager2.js, control/CategoryUpdater.js
Related to
https://github.com/firewalla/firecommit/issues/3405
=> Revert activate category

alarm/AlarmManager2.js, tests/test_alarm_manager2.js
=> Fix recent alarms

sensor/AlarmSensor.js, sensor/InternalScanSensor.js, tests/test_internal_scan_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3529
=> Support manual run policy

scripts/prep/50_prepare_assets_list.sh
Related to
https://github.com/firewalla/firecommit/issues/3561
=> Add nselib files

sensor/InternalScanSensor.js
Related to
[#3529](https://github.com/firewalla/firecommit/issues/3529)
=> Fix clean scanning tasks

net2/HostManager.js, sensor/InternalScanSensor.js, sensor/NseScanPlugin.js, tests/test_internal_scan_sensor.js, tests/test_nse_scan_sensor.js, util/Ranges.js
Related to
[issues/3529](https://github.com/firewalla/firecommit/issues/3529)
[issues/3561](https://github.com/firewalla/firecommit/issues/3561)
=> Fix scan tasks

alarm/AlarmManager2.js, net2/Constants.js, tests/test_alarm_manager2.js
=> Modify to archive ignored alarm

sensor/InternalScanSensor.js
Related to
https://github.com/firewalla/firecommit/issues/3529
=> Fix to extend task life

alarm/AlarmManager2.js, net2/config.json, tests/test_alarm_manager2.js
Related to
[#3583](https://github.com/firewalla/firecommit/issues/3583)
=> Change alarm default state to ready

alarm/AlarmManager2.js, tests/test_alarm_manager2.js
=> Support sync alarm object field

net2/config.json
=> Remove local alarm apply config

alarm/AlarmManager2.js, net2/config.js, tests/test_config.js
=> Fix alarm api

alarm/AlarmManager2.js, sensor/AlarmSensor.js, tests/test_alarm_manager2.js
=> Activate msp timeout alarms

control/CategoryUpdater.js, sensor/CategoryExaminerPlugin.js, tests/test_category_examiner_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3734
=> Ignore bf hit if in exclude domains

platform/gold/files/sysctl.conf, platform/goldpro/files/sysctl.conf, platform/gse/files/sysctl.conf, platform/navy/files/sysctl.conf, platform/pse/files/sysctl.conf, platform/purple/files/sysctl.conf
=> patch purple 1.979 staging

platform/gold/files/sysctl.conf, platform/goldpro/files/sysctl.conf, platform/gse/files/sysctl.conf, platform/navy/files/sysctl.conf, platform/pse/files/sysctl.conf, platform/purple/files/sysctl.conf
=> patch gold 1.979 staging

sensor/CategoryExaminerPlugin.js, tests/test_category_examiner_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3371
=> Fix oisd filter

alarm/Alarm.js, sensor/AlarmSensor.js
Related to
https://github.com/firewalla/firecommit/issues/3575
=> Remove redundant attribute

alarm/Alarm.js, sensor/Guardian.js, tests/test_alarm.js
Related to
https://github.com/firewalla/firecommit/issues/3489#issuecomment-2244387648
=> Fix alarm notice

controllers/netbot.js, lib/ControllerBot.js, net2/Constants.js, sensor/APIRelaySensor.js, sensor/ActionPlugin.js, sensor/AdblockPlugin.js, sensor/DNSCryptPlugin.js, sensor/ExtensionManager.js, sensor/FamilyProtectPlugin.js, sensor/GuardianSensor.js, sensor/MeshVPNPlugin.js, sensor/OSIPlugin.js, sensor/PcapPlugin.js, sensor/SafeSearchPlugin.js, sensor/SystemDNSSensor.js, sensor/UnboundPlugin.js, sensor/VPNRelaySensor.js, tests/test_action_sensor.js, tests/test_netbot.js, tests/test_nse_scan_sensor.js, tests/test_util.js, util/util.js
Related to
[#3846](https://github.com/firewalla/firecommit/issues/3846)
=> Add recording rule change data

tests/test_util.js, util/util.js
Related to
[#3846](https://github.com/firewalla/firecommit/issues/3846)
=> Fix diff object key length

net2/config.json, sensor/SystemRebootSensor.js, tests/test_system_reboot_sensor.js
Related to
https://github.com/firewalla/firecommit/issues/3473
=> Fix os outage

net2/config.json, sensor/SystemRebootSensor.js
Related to
[#3473](https://github.com/firewalla/firecommit/issues/3473)
=> Fix os time

sensor/SafeSearchPlugin.js, tests/test_safesearch_sensor.js
Related to
[#3346](https://github.com/firewalla/firecommit/issues/3346)
[#3965](https://github.com/firewalla/firecommit/issues/3965)
=> Add safesearch hostrecord

controllers/netbot.js
Related to
[#3647](https://github.com/firewalla/firecommit/issues/3647)
=> Add resp ncid

alarm/AlarmManager2.js, tests/test_alarm_manager2.js, tests/test_config.js
Related to
[#3929](https://github.com/firewalla/firecommit/issues/3929)
=> Add alarm cache index

extension/vpnclient/VPNClient.js, extension/vpnclient/WGVPNClient.js, tests/test_vpnclient.js, tests/test_wgvpnclient.js
Related to
[#3914](https://github.com/firewalla/firecommit/issues/3914)
=> Add wireguard ping6 check

control/CategoryUpdaterBase.js, sensor/CategoryExaminerPlugin.js, sensor/CategoryUpdateSensor.js, test/test_category_update_sensor.js
Related to
[issues#4001](https://github.com/firewalla/firecommit/issues/4001)
=> Fix bloom filter hash name

extension/dnsmasq/dnsmasq.js, net2/FireRouter.js, net2/Iptables.js, test/test_firerouter.js
Related to
[issues/3945](https://github.com/firewalla/firecommit/issues/3945)
=> Fix fallback dns ipv6

alarm/Alarm.js, intel/DestInfoIntel.js, migration/RedisMigrator.js, test/test_alarm.js
Related to
[issues/4044](https://github.com/firewalla/firecommit/issues/4044)
=> Add dedup to top level domain

extension/dnsmasq/dnsmasq.js, net2/NetworkProfile.js, net2/NetworkProfileManager.js, net2/SysManager.js, sensor/DnsLoopAvoidanceSensor.js, test/test_dns_loop_avoid_sensor.js, test/test_networkprofile.js, test/test_sysmanager.js
Enhance
[issues/3945](https://github.com/firewalla/firecommit/issues/3945)
=> Fix dns6 checks

platform/platform.sh, scripts/fireupgrade_canary.sh
Related to
[#4011](https://github.com/firewalla/firecommit/issues/4011)
=> fix ota api

extension/dnsmasq/dnsmasq.js
Related to
[#3945](https://github.com/firewalla/firecommit/issues/3945)
=> Fix ip6tables bad address

extension/dnsmasq/dnsmasq.js, scripts/fireupgrade_canary.sh, scripts/fireupgrade_check.sh
Related to
[3945](https://github.com/firewalla/firecommit/issues/3945)
=> Fix wan ip6tables dns fallback

extension/dnsmasq/dnsmasq.js
Related to
[3945](https://github.com/firewalla/firecommit/issues/3945)
=> Fix empty ipv6 dns fallback

scripts/prep/50_prepare_assets_list.sh
Related to
[#3923](https://github.com/firewalla/firecommit/issues/3923)
=> Fix reboot lib symlink

alarm/Alarm.js, sensor/NewDeviceTagSensor.js
issue link:
https://github.com/firewalla/firecommit/issues/4010
=> fix issue-4010, add network info to New Device alarm

controllers/netbot.js, hook/DeviceHook.js, hook/NewDeviceHook.js, net2/Host.js, net2/HostManager.js, net2/HostTool.js, net2/Monitorable.js, net2/TagManager.js
take care of null and undefined string
=> unify localDomain update to Host.js, explicitly parse data on create and update monitorables

control/CategoryUpdater.js, extension/bro/BroNotice.js, net2/BroDetect.js, platform/gold/files/u18/assets.lst, platform/gold/files/u20/assets.lst, platform/gold/files/u22/assets.lst, platform/goldpro/files/assets.lst, platform/gse/files/assets.lst, platform/navy/files/assets.lst, platform/pse/files/assets.lst, platform/purple/files/assets.lst, sensor/CategoryUpdateSensor.js
Add support for auto detect wireguard server
=> Add vpn signature

alarm/AlarmManager2.js
Related to
[3583](https://github.com/firewalla/firecommit/issues/3583)
=> Auto clean dead alarm

controllers/netbot.js, extension/cloud/RenameDeviceAction.js, hook/DeviceHook.js, hook/NewDeviceHook.js, net2/Constants.js, net2/Host.js, net2/HostManager.js, net2/HostTool.js, net2/Monitorable.js, net2/TagManager.js, net2/config.json, package.json, sensor/DeviceNameUpdateSensor.js, sensor/DeviceServiceScanSensor.js, sensor/OldDataCleanSensor.js, test/test_internal_scan_sensor.js
adds host:active:mac as the active mac index, maintained in OldDataCleanSensor
replace most host:mac: updates to Host.update(), so index get updated immediately
=> build mac index host:active:mac

net2/AuditTool.js, sensor/ACLAuditLogPlugin.js, sensor/APCMsgSensor.js, test/test_apcmsg_sensor.js
Related
[4156](https://github.com/firewalla/firecommit/issues/4156)
=> Add ap audit isolate flag

extension/bf/bf.js, sensor/DNSProxyPlugin.js
=> Enhancement:4308, use parameters from cloud for active protect

scripts/sanity_check.sh
remove firerouter warning on box without firerouter
=> fix release with old version of git

net2/Constants.js, sensor/InternetSpeedtestPlugin.js
Related to
[4373](https://github.com/firewalla/firecommit/issues/4373)
=> Add env godebug to speedtest

alarm/Policy.js, alarm/PolicyManager2.js, controllers/netbot.js, net2/NetworkProfile.js
Support route lookup via diagnostic
=> Enhancement:4337

alarm/PolicyManager2.js, control/Block.js
use object for parameter passing
extract common logic into functions
=> Block.js refactor

hook/DeviceHook.js, net2/BroDetect.js, net2/DNSManager.js, net2/FireRouter.js, net2/HostManager.js, net2/HostTool.js, net2/MessageBus.js, net2/SysManager.js, net2/logger.js, sensor/PcapZeekPlugin.js, util/Layer2.js
Reverts firewalla/firewalla#7765
=> Revert "support local flow in bridge mode"

sensor/APFeaturesPlugin.js
[4483](https://github.com/firewalla/firecommit/issues/4483)
=> Add fwapc isolation apply lock

extension/dnsmasq/dnsmasq.js, net2/config.json
[4560](https://github.com/firewalla/firecommit/issues/4560)
=> Add fallback dns6

controllers/netbot.js, event/EventApi.js, sensor/EventSensor.js, test/test_event.js, test/test_netbot.js
[4407](https://github.com/firewalla/firecommit/issues/4407)
=> Add phone-paired notification

net2/HostManager.js, test/test_host_manager.js
[4566](https://github.com/firewalla/firecommit/issues/4566)
=> Fix ap ip4 in init data

alarm/PolicyManager2.js, control/Block.js, control/QoS.js
1. Solution：
- A new feature “app_disturb” to slow down the internet without completely blocking it for a user when the time quota is exhausted .
- some new options and values are added in rule policy, as below:
```
{
"tag": ["userTag:62"],
"guids": [],
"scope": [],
"type": "category",
"protocol": "",
"localPort": "",
"cronTime": "0 0 * * *",
"appTimeUsage": {
"app": "youtube",
"quota": 12,
"period": "0 0 * * *"
},
.....
"action": "app_disturb",  //"app_disturb" is a new value for action
"qdisc": "netem",         //"netem" is a new value for qdisc type
"rateLimit": "200",       //number type, 200 means 200mbits    0.2 means 200kbits
"packetDelay": "200",     // number type in milliseconds
"lossRate": "30"          // packet loss rate, number between 0~100
}
```
- Using TC (Traffic …
=> New Parental Control Feature "app_disturb"

net2/HostManager.js
https://github.com/firewalla/firecommit/issues/4566
=> Fix AP host uuid

control/CategoryEntry.js
For rule that contains udp 443 keep five-tuple based iptables rule as a backup
=> For rule that contains udp 443 keep five-tuple based iptables rule as a backup

controllers/netbot.js, hook/DeviceHook.js, net2/Constants.js, net2/Host.js, net2/HostManager.js, net2/HostTool.js
API issue was introduced in #7773
=> parse only necessary hosts on getHostsAsync, fix set hostDomain

sensor/APFeaturesPlugin.js, test/test_ap_features_plugin.js
https://github.com/firewalla/firecommit/issues/4507
=> Add disable ap acl policy

sensor/APCMsgSensor.js
Take wifi connectivity status into consideration while update device last active time
=> implement enhancement:4471

net2/FlowTool.js
This reverts commit e079619fb14e272c0d528a2f06b8966c29fa32fa.
=> Revert "add ets on flow response"

test/test_NewDeviceTagSensor.js
restore the modules which are mock by mock-require in after function
=> fix ut issue, restore mock

event/EventQueue.js, event/EventRequestHandler.js, test/test_event.js, test/test_event_queue.js
https://github.com/firewalla/firecommit/issues/4812
=> Fix to create queue for state event

event/EventRequestHandler.js, test/test_event.js
https://github.com/firewalla/firecommit/issues/4812
=> Fix to only queue ap state event

net2/config.json, sensor/FastIntelPlugin.js
Use a new bloomfilter category to replace hardcode bloomfilter in FastIntelPlugin
=> Enhancement: implement enhancement 4919

alarm/AppTimeUsageManager.js, alarm/PolicyManager2.js
when switch back from domain-only to default, just enforce policy again with iptables_only to create the 'ag' block rule
=> refine app timelimit block rule

alarm/PolicyManager2.js, controllers/netbot.js, net2/HostManager.js, sensor/Guardian.js
https://github.com/firewalla/firecommit/issues/5007
=> Fix policy queries default limitation

extension/freeradius/freeradius.js, net2/HostManager.js, scripts/list_ap_stations.sh, scripts/techsupport, sensor/APCMsgSensor.js, sensor/FreeRadiusSensor.js, test/test_freeradius.js
https://github.com/firewalla/firecommit/issues/4818
=> 4818 fix radius policy

extension/freeradius/freeradius.js, net2/Tag.js, net2/TagManager.js, sensor/FreeRadiusSensor.js
https://github.com/firewalla/firecommit/issues/4903
=> Fix radius tag depends on new_device_tag

extension/freeradius/freeradius.js
Fix [4903](https://github.com/firewalla/firecommit/issues/4903)
=> Fix to start container if not started

extension/freeradius/freeradius.js, scripts/techsupport, sensor/FreeRadiusSensor.js
https://github.com/firewalla/firecommit/issues/4191
=> Fix mask freeradius config

scripts/list_ap_status.sh
https://github.com/firewalla/proj-ap/issues/370
=> Add last uplink change ts to cap.sh

extension/freeradius/freeradius.js, sensor/FreeRadiusSensor.js
https://github.com/firewalla/firecommit/issues/5379
=> Fix freeradius watch after disable feature
