etc/bro-cron2
use ps -ef to make sure 3 bro process are running instead of checking pid file. If 3 bro process are not running, restart bro service.
=> fix bro process monitoring cron job

scripts/check_reset.sh
1. check if there is usb drive attached. (just do a mount is enough)
2. if there is USB drive mounted, check if there is file name "firewalla_reset" file in / of USB
3. if yes, then call the overlayfs reset function, then delete the file if you can. (prevent next reboot, also go to infiitnte reset)
4. if no, proceed.
=> Script to reset overlayfs based on a flag file on USB

scripts/system-reset-all-overlayfs.sh
Fix a bug in reset for overlayfs , where it needs to remove .bak dirs before rename overlay dirs into .bak ones.
=> remove bak dirs before mv, which would fail otherwise

net2/SpooferManager.js
add delay before walla replies arp spoofing packet to router when an unoccupied ip is probed by arping from router. 
Solve the dhcp failure for China telecom routers and other routers based on udhcpd on busybox.
=> fix dhcp not working issue for some routers

net2/ModeManager.js
this is to ensure revert won't happen during the period of safe launch
=> increase revert timeout to 4 minutes

net2/SysManager.js
[Bug] Fixed a bug that it may fail to generate large transfer alarm if destination ip doesn't have dns.
=> Patch 20171218: bug fix

net2/HostManager.js, scripts/fire-ping.sh, scripts/fire-reboot-normal, scripts/fire-reboot-normalf, scripts/scheduled_reboot.sh, sensor/BoneSensor.js
HW watchdog is needed for situations if there is anything that may cause the kernel to hang.  This is experimental until we see it is stable, should go into production.
Checkin data now will contain user configuration and alarms/... see commit comments on what's is clear text.  This data can eventually be used to recover a firewalla, as well as aid in debugging problems.
=> Enabled HW watchdog / Code to send configs to cloud

extension/dnsmasq/dnsmasq.js
```
Unhandled rejection TypeError: Cannot read property 'start' of null
at Promise (/home/pi/firewalla/extension/dnsmasq/dnsmasq.js:259:12)
at Promise._execute (/home/pi/.node_modules/bluebird/js/release/debuggability.js:300:9)
at Promise._resolveFromExecutor (/home/pi/.node_modules/bluebird/js/release/promise.js:483:18)
at new Promise (/home/pi/.node_modules/bluebird/js/release/promise.js:79:10)
at reload (/home/pi/firewalla/extension/dnsmasq/dnsmasq.js:258:12)
at delay.then (/home/pi/firewalla/util/FlowControl.js:45:23)
at tryCatcher (/home/pi/.node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/pi/.node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/home/pi/.node_modules/bluebird/js/release/promise.js:569:18)
at …
```
=> fix dnsmasq exception

encipher/lib/encipherio.js, lib/Bone.js
we are seen sometimes domain lookup fails (getaddrinfo ENOTFOUND) , this is an issue with node/request.  forcing request to be family:4 is a workaround until someone fixes the root cause, which is in node itself.
https://github.com/request/request-promise-native/issues/6
=> adding family:4 take care issue with node and request module

net2/SysManager.js
This reverts commit b8c8b3b3d857a12b959cad965db5b2d9991e85d0.
=> Revert "BUG: 218.* devices are not loaded during loading init data"

monitor/FlowMonitor.js
this will cause gaming detection always disabled
=> game should be games

net2/IntelManager.js, testLegacy/malware_simulator.js
Fix https://github.com/firewalla/firewalla.ios/issues/609 (ipinfo.io server down causing alarm failed to generate)
=> Fails to fetch ip location info won't impact alarm generation

intel/SSLIntel.js, net2/config.json
=> Add SSL intel into alarm detail

scripts/post_run.sh
=> BUG: should copy watchdog.conf over when it's updated

.github/PULL_REQUEST_TEMPLATE.md
=> remove template for pull request

net2/logger.js
globalLogLevel should be a global variable instead of an instance variable.
=> Fix globalLogLevel bug in logger.js

etc/brotab, scripts/bitbridge-ping.sh
This is a workaround for firewalla/firewalla.ios#858
=> Add cronjob to restart bitbridge7 if necessary

sys/kickstart.js
=> Ignore duplicated SIGTERM processing in kickstart.js

alarm/AlarmManager2.js, control/CategoryUpdater.js, net2/DNSTool.js, net2/Firewalla.js, sys/kickstart.js
should fix this error found at client box.
```
2019-05-05 03:53:07 ERROR CategoryUpdater: Failed to update ipset by category av domain pattern *.netflix.com, err: ChildProcessError: Command failed: redis-cli zrange srdns:pattern:netflix.com 0 -1 | egrep ".*:.*" | sed 's=^=add c_bd_av_set6 = ' | sudo ipset restore -!
ipset v6.29: Error in line 313: Null-valued element, cannot be stored in a hash type of set
`redis-cli zrange srdns:pattern:netflix.com 0 -1 | egrep ".*:.*" | sed 's=^=add c_bd_av_set6 = ' | sudo ipset restore -!` (exited with error code 1)
```
=> Add null v6 address to exclude list

.gitignore, alarm/PolicyManager2.js, control/Block.js, control/CountryUpdater.js, control/install_iptables_setup.sh, controllers/netbot.js, lib/Bone.js, net2/AppTool.js, net2/HostManager.js, net2/Ipset.js, net2/Iptables.js, net2/PolicyManager.js, net2/main.js
- new policy type: remotePort, remoteIpPort, remoteNetPort. 
accepts target of valid entry for ipset type: bitmap:port hash:ip,port hash:net,port
- rework on whitelist, whitelist now work without mangle table and connmark
- device whitelist supported
- remodeled iptables and ipset
=> new feature: remote port block

control/install_iptables_setup.sh, net2/Host.js, net2/NetworkProfile.js, net2/Tag.js
1. vpn client routing supersedes regular routing
2. For different scopes, global < network group < network < device group < device
=> use separate chain for different level of routing/vpnclient rules

cli/heartbeat.js
Sample output
```
...
"diskFree": [
"Filesystem      Size  Used Avail Use% Mounted on",
"udev            962M     0  962M   0% /dev",
"tmpfs           196M   21M  176M  11% /run",
"/dev/mmcblk0p1  5.2G  2.2G  3.0G  42% /media/root-ro",
"/dev/mmcblk0p4  6.0G  238M  5.5G   5% /media/root-rw",
"overlayroot     6.0G  238M  5.5G   5% /",
"tmpfs           977M     0  977M   0% /dev/shm",
"tmpfs           5.0M     0  5.0M   0% /run/lock",
"tmpfs           977M     0  977M   0% /sys/fs/cgroup",
"/dev/mmcblk0p2  1.9G  7.3M  1.8G   1% /data",
"/dev/mmcblk0p3  772M   19M  698M   3% /log",
"tmpfs           196M     0  196M   0% /run/user/1000",
"tmpfs            30M  156K   30M   1% /bspool"
],
...
```
=> capture df -h output in hearbeat

sensor/NetworkMonitorSensor.js
Events are NOT generated when the ping test has a result with the **lossrate** result of the ping test over its limit.
A manual run of sampleOnce is invoked by APP when user enable Internet Quality Test, where APP will pass in some config data to make this manual run much faster than regular ones.
The API take that config as a whole, without referring to system policy on given ping target.
This works fine before since the config provided by APP covered all existing parameters in policy at that time.
However, with some new feature introduced, later on, some extra parameter is added to the underlying sample test of sampleOnce.
But since APP was NOT passing those extra parameters in its config for sampleOnce invocation, the missing parameter triggered an exception during  sampleOnce run, …
=> Fix events NOT being generated in manual run of ping test

lib/ControllerBot.js
full diff
```diff
diff --git a/lib/ControllerBot.js b/lib/ControllerBot.js
index 53d2abc02..f1f095e84 100644
--- a/lib/ControllerBot.js
+++ b/lib/ControllerBot.js
@@ -21,7 +21,10 @@
const log = require('../net2/logger.js')(__filename);
const Trace = require('../util/audit.js');
const rclient = require('../util/redis_manager.js').getRedisClient()
+const pclient = require('../util/redis_manager.js').getPublishClient();
const sem = require('../sensor/SensorEventManager.js').getInstance();
+const f = require('../net2/Firewalla.js');
+const Message = require('../net2/Message.js');
module.exports = class {
// config is the controller json file + the controller section of fullConfig
@@ -184,15 +187,24 @@ module.exports = class {
try {
const appInfo = rawmsg.appInfo;
const mtype = rawmsg.mtype;
+ …
```
=> [trace] refine batch action

extension/vpnclient/openvpn_client@.service.template
everything still goes to /var/log/openvpn_client-CLIENTID.log
https://github.com/firewalla/firewalla/blob/e2cf935406e62c381da251798307d2e167dd47c4/extension/vpnclient/service_start.sh#L9
=> stop ovpnclient from flooding syslog

alarm/AppTimeUsageManager.js, alarm/PolicyManager2.js
for domainonly block policy, in order to make sure block rule can take effect on established connections, first apply it as default mode, then after 10 minutes change back to domain-only mode
=> enhance domainonly block policy

alarm/AppTimeUsageManager.js, alarm/Policy.js, alarm/PolicyManager2.js, control/Block.js, control/QoS.js
Add disturbPeriod for Feature "app disturb"
1. Solution：
- A new feature “app_disturb” to slow down the internet without completely blocking it for a user when the time quota is exhausted .
- some new options and values are added in rule policy, as below:
```
{
"tag": ["userTag:62"],
"guids": [],
"scope": [],
"type": "category",
"protocol": "",
"localPort": "",
"action": "app_block",
"cronTime": "0 0 * * *",
"appTimeUsage": {
"app": "youtube",
"quota": 12,
"period": "0 0 * * *"
},
.....
"qdisc": "netem",            //"netem" is a new value for qdisc type
"disturbMethod": {           //add new "disturbMethod" object to enable disturb function.
"disturbPeriod": 180,      //mandatory value for disturb funciont, disturbPeriod > 0 means open disturb function. 
//disturbPeriod is in seconds …
```
=>  Add disturbPeriod for Feature "app disturb"

alarm/Policy.js, alarm/PolicyManager2.js
Remove enable option and use empty  policy disturbMethod obj to disable app disturb feature.
=> Remove enable option from policy disturbMethod obj.

extension/vpnclient/OpenVPNClient.js, extension/vpnclient/VPNClient.js, net2/FireRouter.js
When OpenVPN client use tcp protocol to connect with OpenVPN server.  It always uses the same WAN port as when establishing a TCP connection even if the primary WAN is recovered. So add a vpn reconnect mechanism for tcp type openvpn client when WAN switch happened.
=> Fix Bug of OpenVPN not failback when use tcp proto

sensor/NewDeviceTagSensor.js, test/test_NewDeviceTagSensor.js
AP might detected by neighbor discovery or other way before discoveried by DHCP, for these device which with Firewalla OUI but dhcpName is not avaliable when doing isFirewallaAP check, wait 10s then check again
=> fix issue, some celing AP was added into quarantine group
